<a href="https://colab.research.google.com/github/Anna72/lab-lkfs/blob/main/fails_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = pd.read_csv("fails_dataset.csv", encoding = 'utf-8', delimiter=';',sep='\t', comment='#',error_bad_lines=False)
data.head(23)

             Номер заказа  ... Длительность (целых часов)
0   Без заказа / операции  ...                       10.0
1   Без заказа / операции  ...                        2.0
2   Без заказа / операции  ...                       13.0
3   Без заказа / операции  ...                        1.0
4   Без заказа / операции  ...                        0.0
5   Без заказа / операции  ...                       13.0
6   Без заказа / операции  ...                      451.0
7   Без заказа / операции  ...                        0.0
8   Без заказа / операции  ...                        0.0
9   Без заказа / операции  ...                        2.0
10  Без заказа / операции  ...                        0.0
11  Без заказа / операции  ...                     1235.0
12  Без заказа / операции  ...                        1.0
13  Без заказа / операции  ...                        3.0
14  Без заказа / операции  ...                       97.0
15  Без заказа / операции  ...                      128.0
16  Без заказа / операции  ...                       67.0
17  Без заказа / операции  ...                        6.0
18  Без заказа / операции  ...                       17.0
19  Без заказа / операции  ...                      215.0
20  Без заказа / операции  ...                      171.0
21  Без заказа / операции  ...                        8.0
22  Без заказа / операции  ...                      494.0

[23 rows x 10 columns]

In [ ]:
data.shape

(381633, 10)

In [ ]:
data['Номер заказа'].nunique()

36954

In [ ]:
data['Номер заказа'].value_counts()

W_17_01166    362
W_17_08000    289
W_16_24099    275
W_17_12228    252
W_17_18612    241
             ...
W_18_19158      1
W_16_04911      1
W_18_30997      1
W_17_19096      1
W_15_19987      1
Name: Номер заказа, Length: 36953, dtype: int64

In [ ]:
#data = data[~data.'Номер заказа'.str.contains("Без заказа")]
data = data[~data['Номер заказа'].isin(['Без заказа / операции'])]
data['Номер заказа'].value_counts()

W_17_01166    362
W_17_08000    289
W_16_24099    275
W_17_12228    252
W_17_18612    241
             ...
W_18_19158      1
W_16_04911      1
W_18_30997      1
W_17_19096      1
W_15_19987      1
Name: Номер заказа, Length: 36953, dtype: int64

In [ ]:
data.head(10)

    Номер заказа  ... Длительность (целых часов)
492   W_17_02331  ...                       11.0
511   W_16_19099  ...                       10.0
512   W_14_16659  ...                        0.0
513   W_14_16659  ...                        0.0
514   W_14_16659  ...                        0.0
515   W_14_16659  ...                        0.0
516   W_14_16683  ...                        0.0
517   W_14_16683  ...                        0.0
518   W_14_16683  ...                       34.0
519   W_14_16683  ...                        2.0

[10 rows x 10 columns]

In [ ]:
data1 = data[data['Номер заказа'].isin(['W_17_01166'])]
data1
# data1  заказ W_17_01166

       Номер заказа  ... Длительность (целых часов)
46949    W_17_01166  ...                        4.0
46950    W_17_01166  ...                        0.0
46951    W_17_01166  ...                       10.0
46952    W_17_01166  ...                       22.0
46953    W_17_01166  ...                       37.0
...             ...  ...                        ...
359649   W_17_01166  ...                       20.0
359650   W_17_01166  ...                       33.0
359651   W_17_01166  ...                       58.0
369525   W_17_01166  ...                        0.0
369526   W_17_01166  ...                       16.0

[362 rows x 10 columns]

In [ ]:
data1['Обозначение оборудования'].value_counts()

Leistritz_LWN120IW                224
TIBO                               87
DMG_CTX_BETA_1250_TC_4A            35
MAZAK_QTS_200                      16
Name: Обозначение оборудования, dtype: int64

In [ ]:
data1.sort_values(by=['Дата-время начала', 'Дата-время окончания'])

       Номер заказа  ... Длительность (целых часов)
119587   W_17_01166  ...                      101.0
47118    W_17_01166  ...                       34.0
47041    W_17_01166  ...                      235.0
119767   W_17_01166  ...                       47.0
47010    W_17_01166  ...                        0.0
...             ...  ...                        ...
47100    W_17_01166  ...                        0.0
47053    W_17_01166  ...                      148.0
47047    W_17_01166  ...                       23.0
47101    W_17_01166  ...                        0.0
119579   W_17_01166  ...                        0.0

[362 rows x 10 columns]

In [ ]:
data1.shape

(362, 10)